public class CreditCard{
	// Initialize variables pertaining to the card. 
	private String cardNumber; 
	private double expenses; 
	// Controls the amount of tries to get the Card Number.
	private int numTries = 3; 
	private String pass; 
	
	// Card Constructor. 
	public CreditCard(String newPass){
		this.cardNumber = "123456789"; 
		this.pass = newPass;
	} // End of Constructor. 
	
	// Method to add charges to the account. 
	public void charge(double amount){
		expenses += amount; 
	} // End of charge. 
	
	// Method to get the Card Number. Password must equal the password generated by Card constructor. 
	public String getCardNumber(String password){
		if (numTries == 0){
			return "Sorry you've exhausted all of your tries.";
		}
		else if (pass.equals(password)){
			numTries = 3; 
			return "Your card number is: " +cardNumber;
		}
		else {
			numTries--;
			return "Incorrect Password. You have " + numTries + " tries left."; 
		}
	} // End of getCardNumber. 
	
	public static void main(String[] args){
		System.out.println("Test however."); 
	}
	
}